# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/recovery_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(310, 230, 81, 71))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 66, 31))
        self.label_2.setObjectName("label_2")
        self.send_code_button = QtWidgets.QPushButton(Dialog)
        self.send_code_button.setGeometry(QtCore.QRect(130, 80, 141, 31))
        self.send_code_button.setObjectName("send_code_button")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 66, 31))
        self.label_3.setObjectName("label_3")
        self.submit_button = QtWidgets.QPushButton(Dialog)
        self.submit_button.setGeometry(QtCore.QRect(130, 220, 141, 31))
        self.submit_button.setObjectName("submit_button")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 66, 51))
        self.label_4.setObjectName("label_4")
        self.number_edit = QtWidgets.QTextEdit(Dialog)
        self.number_edit.setGeometry(QtCore.QRect(100, 40, 201, 31))
        self.number_edit.setObjectName("number_edit")
        self.code_edit = QtWidgets.QTextEdit(Dialog)
        self.code_edit.setGeometry(QtCore.QRect(100, 130, 201, 31))
        self.code_edit.setObjectName("code_edit")
        self.new_password_edit = QtWidgets.QTextEdit(Dialog)
        self.new_password_edit.setGeometry(QtCore.QRect(100, 180, 201, 31))
        self.new_password_edit.setObjectName("new_password_edit")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Número:"))
        self.send_code_button.setText(_translate("Dialog", "Obter código"))
        self.label_3.setText(_translate("Dialog", "Código:"))
        self.submit_button.setText(_translate("Dialog", "Submeter"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p>Password</p><p>Nova:</p><p><br/></p></body></html>"))
